spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fantasticblog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2333
  redis:
    port: 6379

logging:
#  file:
#    path: log/blog-dev.log
  level:
    root: info
#    cc.lijad: warn

minio:
  endpoint: http://192.168.118.128:9000
  accesskey: 92OI3EQLYKNW7JHKEPZ9
  secretKey: aQOzzhsSYx0a9vQMO9mjEUUSqWxec5idOT7St9RN
  bucket: blog

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl