server:
  port: 8888

spring:
  profiles:
    active: dev

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-not-delete-value: 0
      logic-delete-value: 1
