spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/fantasticblog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@2333
  redis:
    host: 127.0.0.1
    password: 2333
    port: 6379

logging:
  file:
    path: /home/log/fantasticblog/frontend/blog-pro.log
  level:
    root: warn

minio:
  endpoint: http://lijad.cc:9000
  accesskey: y3Hzd3Lkf92O2GHz
  secretKey: cwTgXzJ8PTr3kLxsDe0cdZIUIolnMOsg
  bucket: blog
