server:
  port: 9999

spring:
  application:
    name: blog-frontend
  profiles:
    active: dev

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-not-delete-value: 0
      logic-delete-value: 1
    #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/fantasticblog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 2333


#minio:
#  endpoint: http://192.168.118.128:9000
#  accesskey: 92OI3EQLYKNW7JHKEPZ9
#  secretKey: aQOzzhsSYx0a9vQMO9mjEUUSqWxec5idOT7St9RN
#  bucket: blog

#logging:
#  file:
#    path: log/blog-dev.log